### ISSUE TITLE
packaging 25.0 breaks recipe build

### ISSUE THREAD

**Issue by ssppkenny** [flet-dev/mobile-forge#39]
### Describe the bug

I have created several recipes for my app, which I was able to compile with packaging 24.2 for python 3.12.9
Now when I start forge android readpdfutils, I get the following error message: 

ile "/Users/username/code/python/mobile-forge/build/cp312/readpdfutils/1.0.5/venv3.12-android_24_arm64_v8a/build/lib/python3.12/site-packages/packaging/tags.py", line 556, in android_platforms
api_level = platform.android_ver().api_level  # type: ignore[attr-defined]
^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'platform' has no attribute 'android_ver'

Is it possible to force packaging=24.2 for forge?

I think, the problem is that packaging.25.0 requires python 3.13.
But I do no have python 3.13 for android.

Python 3.12.9 was compiled with the help of the following repo
https://github.com/flet-dev/python-android

pyproject.toml for mobile-forge specifies packaging = 24.0.

But the build uses cached packaging-25.0-py3-none-any.whl.metadata (3.3 kB).

meta.yaml for readpdfutils

package:
  name: readpdfutils
  version: 1.0.5

requirements:
  build:
    - numpy 1.26.4
  host:
    - flet-libpdfium 6694

build:
  number: 0

requirements:
  build:
    - numpy 1.26.4
  host:
    - flet-libpdfium 6694

meta.yaml for flet-libpdfium

package:
  name: flet-libpdfium
  version: "6694"

source:
  url: https://github.com/paulocoutinhox/pdfium-lib/releases/download/6694/android.tgz

build.sh for flet-libpdfium

#!/bin/bash
set -eu

echo $(pwd)

mkdir -p $PREFIX/lib
cp lib/$ANDROID_ABI/libpdfium.so $PREFIX/lib

### Expected behavior

packaging 24.0 or 24.2 can be used.

### Environment

- Operating System:
- Python version:
- Software versions:
  - Briefcase:
  - Toga:
  - ...

### Logs

```

```

**Comment by ssppkenny** [comment]
I was able to force cross environment to use packaging 24.0 version using a hack in cross.py, adding a line after "install"
        self.run(
            logfile,
            (["build-pip"] if build else ["python", "-m", "pip"])
            + [
                "install",
                "packaging==24.0",
                "--disable-pip-version-check",
            ]
